### ISSUE TITLE
Panic building on Windows running: "rm" "-rf" ".termbox" (file not found)

### ISSUE THREAD

**Issue by val-ms** [gchp/termbox-sys#23]
I experienced a panic when building `termbox-sys` on Windows as a dependency of the `rex` crate.

The output looked like this:

```
error: failed to run custom build command for `termbox-sys v0.2.12`

Caused by:
  process didn't exit successfully: `C:\Users\build\AppData\Local\Temp\cargo-installKElqYD\release\build\termbox-sys-2c803b9c27aec6fd\build-script-build` (exit code: 101)
  --- stdout
  running: "rm" "-rf" ".termbox"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\build\.cargo\registry\src\github.com-1ecc6299db9ec823\termbox-sys-0.2.12\build.rs:94:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rex v0.1.0`, intermediate artifacts can be found at `C:\Users\build\AppData\Local\Temp\cargo-installKElqYD`

Caused by:
  build failed
```

**Comment by neelkarma** [comment]
Same with me:
```
error: failed to run custom build command for `termbox-sys v0.2.12`

Caused by:
  process didn't exit successfully: `C:\Users\nsdjs\Documents\Programming\Rust\hackertype\target\debug\build\termbox-sys-2f9b5f7709c33c52\build-script-build` (exit code: 101)
  --- stdout
  running: "rm" "-rf" ".termbox"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\nsdjs\.cargo\registry\src\github.com-1ecc6299db9ec823\termbox-sys-0.2.12\build.rs:94:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
For me, `termbox-sys` was a dependency of `rustbox`

**Comment by Ch3nYe** [comment]
same with me:
```
error: failed to run custom build command for `termbox-sys v0.2.12`
Caused by:
  process didn't exit successfully: `E:\RustProject\iota\target\debug\build\termbox-sys-27c2e71ca970c78d\build-script-build` (exit code: 101)
  --- stdout
  running: "rm" "-rf" ".termbox"
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }',
```

wanna know how to solve this, 😢

**Comment by LoZeno** [comment]
This error has never been addressed?
[This command in the build.rs](https://github.com/gchp/termbox-sys/blob/a078170279dbe75d541c0a33714a8843ebc67c88/build.rs#L34) is simply unsupported in Windows...
